pipeline 
    agent any 
        tool {
            maven 'maven3'
            
    stage ( SCM clone)
        steps {
            readTrusted 'readTrusted \'https://github.com/223038472/simple-java-maven-app.git\''
        }
    }
    stages {
        steps('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        } 
        stage('Deploy')
        steps {
            sh 'mavenHome/bin/mvn deploy'
            }
            
        nexusArtifactUploader artifacts: [
            [
            artifactId: 'my-app', 
            classifier: '', 
            file: 'target/my-app-1.0.jar', 
            type: 'jar'
            ]

        ],
    
        credentialsId: 'RR1zWAiA', 
        groupId: 'com.mycompany.app', 
        nexusUrl: ' https://nexusprod.corp.intranet:8443/', 
        nexusVersion: 'nexus3', 
        protocol: 'https', 
        repository: 'maven/releases', 
        version: 'Nexus3'

    }
}
